// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/family-graph-options/OptionA.tsx": () => import("../components/mockups/family-graph-options/OptionA.tsx"),
  "./components/mockups/family-graph-options/OptionB.tsx": () => import("../components/mockups/family-graph-options/OptionB.tsx"),
  "./components/mockups/family-graph-options/OptionC.tsx": () => import("../components/mockups/family-graph-options/OptionC.tsx"),
  "./components/mockups/family-graph-options/OptionD.tsx": () => import("../components/mockups/family-graph-options/OptionD.tsx")
};
